---
title: "1.0_candidate-genes_models.Rmd"
author: "Andrea Estandia"
date: "02/08/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, echo=FALSE}
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
options(scipen = 999)
```

```{r, echo=FALSE}
source("./src/ae-candidate-gene-analysis_source.R")
```

```{r}
subset <-
  read_csv(file.path(data_path, "20211001_df_cand_AE+SMC+BR.csv")) %>%
  mutate_if(is.character, as.factor)
```

Process CREB1
```{r}
CREB1 <- subset %>%
  mutate(population=ifelse(migrant=="yes", "Migrant", as.character(population))) %>% 
  filter(mean_creb1 != "NA") %>% 
  filter(population != "Australia") %>% 
  filter(population!="Migrant") %>% 
  filter(population!="Erromango")
  
CREB1$disp_index <-
  rescale(CREB1$disp_index, to = c(0, 1))
```

Process ADCYAP1
```{r}
ADCYAP <- subset %>%
  drop_na(mean_adcyap) %>% 
  mutate(population=ifelse(migrant=="yes", "Migrant", as.character(population))) %>% 
  filter(population != "Australia") %>% 
  filter(population!="Migrant") %>% 
  filter(population!="Erromango")

ADCYAP$disp_index <- rescale(ADCYAP$disp_index, to =c(0,1))
ADCYAP$isolation_index <- rescale(ADCYAP$isolation_index, to = c(0, 1))
```

```{r}
cov_matrix <- read_csv(file.path(data_path, "pop_covariance_matrix.csv"))

#Remove Pentecost and Ambae because they're not present in the main CREB1 dataset and Australia because it's the population source
cov_matrix_creb1 <- as.data.frame(cov_matrix[c(-1, -3, -16), c(-1, -3, -16)])
row.names(cov_matrix) <- colnames(cov_matrix)

#Remove Ambae because it's not present in the main ADCYAP1 dataset and Australia because it's the source 
cov_matrix_adcyap <- as.data.frame(cov_matrix[c(-1, -3), c(-1, -3)])
row.names(cov_matrix_adcyap) <- colnames(cov_matrix_adcyap)

```

```{r}
heatmap(as.matrix(cov_matrix),symm=T,col=brewer.pal(9,"Blues"),labCol = FALSE)
```

Prior for CREB1 and ADCYAP1
```{r}
prior1 = c(
  prior(normal(0,20), coef="disp_index"),
  prior(normal(0,20), coef="age_myr")
)
```

Bayesian regression - CREB1
```{r}
null_creb1 <- brm(
  mean_creb1 ~ 
    (1 | gr(population,cov=cov_matrix)),
  data = CREB1,
  data2=list(cov_matrix=cov_matrix),
  warmup = 400,
  iter   = 4000,
  chains = 4,
  seed = 123, 
  control = list(max_treedepth = 30, adapt_delta = 0.99))

model_creb1 <- brm(
  mean_creb1 ~ disp_index + 
    age_myr +
    (1 | gr(population,cov=cov_matrix)),
  data = CREB1,
  data2=list(cov_matrix=cov_matrix),
  warmup = 400,
  iter   = 4000,
  chains = 4,
  prior = prior1,
  seed = 123, 
  control = list(max_treedepth = 15, adapt_delta = 0.99))

plot_creb <- model_creb1 %>%
  spread_draws(b_Intercept, r_population[population,]) %>%
  mutate(condition_mean = b_Intercept + r_population) %>%
  ggplot(aes(y = fct_reorder(population,condition_mean), x = condition_mean)) +
  theme_minimal() + 
  xlab("Mean CREB1 length (bp)") + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        axis.title.y = element_blank()) +
  stat_halfeye() 

model_creb1$loo <- loo(model_creb1)
null_creb1$loo <- loo(null_creb1)
loo_compare(null_creb1$loo,model_creb1$loo)
```

Posterior predictive checks and conditional effects - CREB1
```{r}
pp_check(model_creb_poisson, nsamples =1000)
conditional_effects(model_creb_poisson)
```


Bayesian regression - ADCYAP
```{r}
null_adcyap <- brm(
  mean_adcyap ~ 1+ (1 | gr(population,cov=cov_matrix_adcyap)),
  data = ADCYAP,
  data2=list(cov_matrix_adcyap=cov_matrix_adcyap),
  warmup = 400,
  iter   = 4000,
  chains = 4,
  seed = 123, 
  control = list(max_treedepth = 15, adapt_delta = 0.99))

model_adcyap <- brm(
  mean_adcyap ~ disp_index + 
    age_myr+
    (1 | gr(population,cov=cov_matrix)),
  data = ADCYAP,
  data2=list(cov_matrix=cov_matrix),
  warmup = 400,
  iter   = 4000,
  prior = prior1,
  chains = 4,
  seed = 123, 
  control = list(max_treedepth = 15, adapt_delta = 0.99))

plot_adcyap <- model_adcyap %>%
  spread_draws(b_Intercept, r_population[population,]) %>%
  mutate(condition_mean = b_Intercept + r_population) %>%
  ggplot(aes(y = fct_reorder(population,condition_mean), x = condition_mean)) +
  theme_minimal() + 
  xlab("Mean ADCYAP1 length (bp)") + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        axis.title.y = element_blank()) +
  stat_halfeye() 

model_adcyap$loo <- loo(model_adcyap)
null_adcyap$loo <- loo(null_adcyap)
loo_compare(null_adcyap$loo,model_adcyap$loo)
```

Posterior predictive checks and conditional effects - ADCYAP1
```{r}
pp_check(model_adcyap, nsamples =1000)
conditional_effects(model_adcyap)
```


MCP models

```{r}
mcp_null_creb_age = mcp(
  list(mean_creb1 ~ 1),
  data = CREB1,
  par_x="age_myr",
  iter = 4000,
  adapt = 400,
  chains = 4
)

mcp_null_creb_disp = mcp(
  list(mean_creb1 ~ 1),
  data = CREB1,
  par_x="disp_index",
  iter = 4000,
  adapt = 400,
  chains = 4
)

priorfit_age = list(int_1 = "dnorm(550,20)",
                 int_2 = "dnorm(550,20)",
                 age_myr_2 = 1,
                 cp_1 = "dnorm(0.1,0.1)")

priorfit_disp = list(int_1 = "dnorm(550,20)",
                 int_2 = "dnorm(550,20)",
                 disp_index_2 = 1,
                 cp_1 = "dnorm(0.5,0.5)")

mcp_creb_age = mcp(list(mean_creb1 ~ 1,
          ~ age_myr + (1 | population) + (1 | cluster)),
          data = CREB1,
          prior = priorfit_age,
          iter = 10000,
          adapt = 1000,
          chains = 4)

mcp_creb_disp = mcp(list(mean_creb1 ~ 1,
          ~ disp_index + (1 | population) + (1 | cluster)),
          data = CREB1,
          prior = priorfit_disp,
          iter = 10000,
          adapt = 1000,
          chains = 4)

ggfit3 <- 
  plot.mcpfit.andrea(mcp_creb_disp, q_predict = T, quantiles = c(0.11, 0.89), reverse_xaxis = TRUE) +
    # Add jittered points
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank(),
    axis.line = element_line()
  ) +
  theme(legend.position = "none",
        panel.background = element_blank()) +
  labs(y = "Mean CREB1 length (bp)\n", x = "\nDispersal Index")

ggfit3

ggfit2 <-
  plot.mcpfit.andrea(mcp_creb_age, q_predict = T, quantiles = c(0.1, 0.89)) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank(),
    axis.line = element_line()
  ) +
  theme(legend.position = "none",
        panel.background = element_blank()) +
  labs(y = "Mean CREB1 length (bp)\n", x = "\nPopulation Age (Mya)") + geom_text(data = data.frame(x = 0.18, y = 563.53306667085, 
    label = "Tasmania"), mapping = aes(x = x, y = y, label = label), 
    size = 3.8, angle = 0L, lineheight = 1L, hjust = 1L, 
    vjust = 0.5, colour = "black", family = "sans", fontface = "plain", 
    inherit.aes = FALSE, show.legend = FALSE) + annotate(
    "curve",
    yend = 560.3,
    xend = 0.195,
    y = 562.8,
    x = 0.175,
    size = 0.25,
    curvature = 0,
    alpha = 0.7,
    colour = "#404040",
    arrow = arrow(length = unit(2, "mm")))

ggfit2
models_output <- ggfit2+ggfit3+plot_layout(ncol=1)+plot_annotation(tag_levels = 'A')

mcp_null_creb_disp$loo = loo(mcp_null_creb_disp)
mcp_creb_disp$loo = loo(mcp_creb_disp)
loo_compare(mcp_null_creb_disp$loo, mcp_creb_disp$loo)

mcp_null_creb_age$loo = loo(mcp_null_creb_age)
mcp_creb_age$loo = loo(mcp_creb_age)
loo_compare(mcp_null_creb_age$loo, mcp_creb_age$loo)
```

```{r}
library(kableExtra)
library(broom)
tidy(model_creb1) %>% 
  filter(grepl(term, pattern = '^b')) %>% 
  mutate(term = c('Intercept', 'Math', 'Male', 'General', 'Academic')) %>% 
  rename_all(str_to_title) %>% 
  kable(digits = 2)

```
