---
  title: "1.0_tests"
author: "Andrea Estandia<br>"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
  toc: true
toc_depth: 4
editor_options:
  chunk_output_type: console
---
  <br>
  
```{r setup, echo=FALSE}
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
options(scipen = 999)
```

```{r, echo=FALSE}
source("./src/ae-candidate-gene-analysis_source.R")
```

Read data and create subset by gene

```{r, echo=FALSE}
df <-
  read_csv(file.path(data_path, "20211001_df_cand_AE+SMC+BR.csv")) %>%
  mutate_if(is.character, as.factor)

CREB1 <- df %>%
  drop_na(mean_creb1) %>% 
  mutate(mean_creb1=as.numeric(unlist(mean_creb1))) %>% 
  filter(mean_creb1!=552.5)

ADCYAP <- df %>%
  drop_na(mean_adcyap)

CLOCK <- df %>%
  drop_na(mean_clock)

NPAS2 <- df %>%
  drop_na(mean_npas2)
```

ANOVA and Tukey tests for DRD4 and SERT
```{r}
list_variants <- colnames(df[,grep("DRD|SERT", colnames(df))])
subset_variants <- df[,grep("DRD|SERT", colnames(df))]

list_variants_out <- list()
for (variant in list_variants){
  tmp <- df %>%
    dplyr::select(name, population, variant, locator) %>%
    drop_na(variant)
  print(summary(aov(as.formula(paste0(as.character(variant), "~ population")), data = tmp)))
  print(TukeyHSD(aov(as.formula(paste0(as.character(variant), "~ population")), data = tmp)))
}
```

Summary stats, ANOVA and Tukey tests for candidate microsatellite
```{r}
list_variants <- colnames(df[,grep("mean_adcyap|mean_npas|mean_clock|mean_creb", colnames(df))])
subset_variants <- df[,grep("mean_adcyap|mean_npas|mean_clock|mean_creb", colnames(df))]

list_variants_out <- list()
for (variant in list_variants){
  tmp <- df %>%
    dplyr::select(name, population, variant, locator) %>%
    drop_na(variant)
  print(summary(aov(as.formula(paste0(as.character(variant), "~ population")), data = tmp)))
  print(TukeyHSD(aov(as.formula(paste0(as.character(variant), "~ population")), data = tmp)))
}

for (variant in list_variants){
  print(group_by(df, population) %>%
          summarise(
            count = n(),
            mean = mean(get(variant), na.rm = TRUE),
            sd = sd(get(variant), na.rm = TRUE)
          ))
}
```

BRMS models exploring changes in candidate gene lengths by population

```{r}
snp83 <-df %>%
    dplyr::select(population, DRD12_snp83) %>%
    drop_na(DRD12_snp83)

get_prior(DRD12_snp83 ~ population,
  data = snp83)

bprior <- prior(normal(0.5,0.5), class = b)

mod_snp83 <- brm(
  DRD12_snp83 ~ population,
  data = snp83,
  family=bernoulli(),
  iter = 10000,
  prior=bprior
)

mod_creb1 <- brm(
  mean_creb1 ~ population,
  data = CREB1
)

CREB1$population <- droplevels(CREB1$population)

mod_creb1_plot <- CREB1 %>%
  mutate(population = factor(
      population,
      levels = c(
        "Australia",
        "Tasmania",
        "NZ",
        "Chatham_Island",
        "Norfolk_Island",
        "Heron_Island",
        "Lord_Howe_Island",
        "Grand_Terre",
        "Ouvea",
        "Lifou",
        "Mare",
        "Ambrym",
        "Efate",
        "Gaua",
        "Malekula",
        "Espiritu_Santo",
        "Tanna"
      )
    )) %>% 
  data_grid(population, cluster) %>%
  #filter(population != "Pentecost") %>%
  add_fitted_draws(mod_creb1) %>%
  ggplot(aes(x = .value, y = population)) +
  stat_dotsinterval(quantiles = 50,size=2)+
  scale_fill_manual(values = c("#ccb416", "#538699"))+
  scale_color_manual(values = c("#ccb416", "#538699"))+
  theme_minimal() +
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.text.x = element_text(hjust=1, size = text_size),
    axis.title.y = element_blank(),
    axis.title = element_text(size = text_size),
    plot.title = element_text(face = "bold"),
    plot.subtitle = element_text(color = "#424242"))+
  labs(
    x = "\nCREB1 mean length (bp)",
    title = "Posterior estimates of the group means"
  )
```

```{r}
mod_clock <- brm(
  mean_clock ~ population,
  data = CLOCK
)

CLOCK$population <- droplevels(CLOCK$population)

mod_clock_plot <- 
  CLOCK %>%
  mutate(population = factor(
      population,
      levels = c(
        "Australia",
        "Tasmania",
        "NZ",
        "Chatham_Island",
        "Norfolk_Island",
        "Heron_Island",
        "Lord_Howe_Island",
        "Grand_Terre",
        "Ouvea",
        "Lifou",
        "Mare",
        "Ambrym",
        "Gaua",
        "Malekula",
        "Erromango",
        "Pentecost",
        "Espiritu_Santo",
        "Efate",
        "Tanna"
      )
    )) %>% 
  data_grid(population, cluster) %>%
  #filter(population != "Pentecost") %>%
  add_fitted_draws(mod_clock) %>%
  ggplot(aes(x = .value, y = population)) +
  stat_dotsinterval(quantiles = 50,size=2)+
  scale_fill_manual(values = c("#ccb416", "#538699"))+
  scale_color_manual(values = c("#ccb416", "#538699"))+
  theme_minimal() +
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.text.x = element_text(hjust=1, size = text_size),
    axis.title.y = element_blank(),
    axis.title = element_text(size = text_size),
    plot.title = element_text(face = "bold"),
    plot.subtitle = element_text(color = "#424242"))+
  labs(
    x = "\nCLOCK mean length (bp)",
    title = "Posterior estimates of the group means"
  )

```

```{r}
mod_adcyap1 <- brm(
  mean_adcyap ~ population,
  data = ADCYAP
)

ADCYAP$population <- droplevels(ADCYAP$population)

mod_adcyap_plot <- ADCYAP %>%
  mutate(population = factor(
      population,
      levels = c(
        "Australia",
        "Tasmania",
        "NZ",
        "Chatham_Island",
        "Norfolk_Island",
        "Heron_Island",
        "Lord_Howe_Island",
        "Grand_Terre",
        "Ouvea",
        "Lifou",
        "Mare",
        "Ambrym",
        "Gaua",
        "Malekula",
        "Erromango",
        "Pentecost",
        "Espiritu_Santo",
        "Efate",
        "Tanna"
      )
    )) %>% 
  data_grid(population, cluster) %>%
  #filter(population != "Pentecost") %>%
  add_fitted_draws(mod_adcyap1) %>%
  ggplot(aes(x = .value, y = population)) +
  stat_dotsinterval(quantiles = 50,size=2)+
  scale_fill_manual(values = c("#ccb416", "#538699"))+
  scale_color_manual(values = c("#ccb416", "#538699"))+
  theme_minimal() +
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.text.x = element_text(hjust=1, size = text_size),
    axis.title.y = element_blank(),
    axis.title = element_text(size = text_size),
    plot.title = element_text(face = "bold"),
    plot.subtitle = element_text(color = "#424242"))+
  labs(
    x = "\nADCYAP1 mean length (bp)",
    title = "Posterior estimates of the group means"
  )
```

```{r}
mod_npas <- brm(
  mean_npas2 ~ population,
  data = NPAS2
)

NPAS2$population <- droplevels(NPAS2$population)

mod_npas_plot <-
  NPAS2 %>%
  mutate(population = factor(
      population,
      levels = c(
        "Australia",
        "Tasmania",
        "NZ",
        "Chatham_Island",
        "Norfolk_Island",
        "Heron_Island",
        "Lord_Howe_Island",
        "Grand_Terre",
        "Ouvea",
        "Lifou",
        "Mare",
        "Ambrym",
        "Gaua",
        "Malekula",
        "Erromango",
        "Pentecost",
        "Espiritu_Santo",
        "Efate",
        "Tanna"
      )
    )) %>% 
  data_grid(population, cluster) %>%
  #filter(population != "Pentecost") %>%
  add_fitted_draws(mod_npas) %>%
  ggplot(aes(x = .value, y = population)) +
  stat_dotsinterval(quantiles = 50,size=2)+
  scale_fill_manual(values = c("#ccb416", "#538699"))+
  scale_color_manual(values = c("#ccb416", "#538699"))+
  theme_minimal() +
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.text.x = element_text(hjust=1, size = text_size),
    axis.title.y = element_blank(),
    axis.title = element_text(size = text_size),
    plot.title = element_text(face = "bold"),
    plot.subtitle = element_text(color = "#424242"))+
  labs(
    x = "\nNPAS2 mean length (bp)",
    title = "Posterior estimates of the group means"
  )
```

```{r}
mod_cand <- mod_creb1_plot+mod_clock_plot+mod_npas_plot+mod_adcyap_plot

ggsave(
  plot = mod_cand,
  filename = "mod_cand.svg",
  path = figures_path,
  device = "svg",
  width = 1000,
  height = 700,
  dpi = 400
)
```

Export models as tables
```{r}
tab_model(mod_snp83,file = "snp83")
```

